//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource4() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Components.Resource4", typeof(Resource4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\autobuz101.png.
        /// </summary>
        internal static string autobuz101_png {
            get {
                return ResourceManager.GetString("autobuz101.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\autobuz102.png.
        /// </summary>
        internal static string autobuz102_png {
            get {
                return ResourceManager.GetString("autobuz102.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\autobuz103.png.
        /// </summary>
        internal static string autobuz103_png {
            get {
                return ResourceManager.GetString("autobuz103.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\default_map_new.png.
        /// </summary>
        internal static string default_map_new_png {
            get {
                return ResourceManager.GetString("default_map_new.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\metrou1.png.
        /// </summary>
        internal static string metrou1_png {
            get {
                return ResourceManager.GetString("metrou1.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\tramvai10.png.
        /// </summary>
        internal static string tramvai10_png {
            get {
                return ResourceManager.GetString("tramvai10.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\tramvai11png.png.
        /// </summary>
        internal static string tramvai11_png {
            get {
                return ResourceManager.GetString("tramvai11.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Maps\tramvai12.png.
        /// </summary>
        internal static string tramvai12_png {
            get {
                return ResourceManager.GetString("tramvai12.png", resourceCulture);
            }
        }
    }
}
