//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Components.Resource3", typeof(Resource3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Autobuz_101.png.
        /// </summary>
        internal static string Autobuz_101_png {
            get {
                return ResourceManager.GetString("Autobuz_101.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bk_bun.jpg.
        /// </summary>
        internal static string bk_bun_jpg {
            get {
                return ResourceManager.GetString("bk_bun.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bk_final.jpg.
        /// </summary>
        internal static string bk_final_jpg {
            get {
                return ResourceManager.GetString("bk_final.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bk1.jpg.
        /// </summary>
        internal static string bk1_jpg {
            get {
                return ResourceManager.GetString("bk1.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bk2.jpg.
        /// </summary>
        internal static string bk2_jpg {
            get {
                return ResourceManager.GetString("bk2.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bk3.jpg.
        /// </summary>
        internal static string bk3_jpg {
            get {
                return ResourceManager.GetString("bk3.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bus_gif.gif.
        /// </summary>
        internal static string bus_gif_gif {
            get {
                return ResourceManager.GetString("bus_gif.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\bus_video.mp4.
        /// </summary>
        internal static string bus_video_mp4 {
            get {
                return ResourceManager.GetString("bus_video.mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\default_map1.png.
        /// </summary>
        internal static string default_map1_png {
            get {
                return ResourceManager.GetString("default_map1.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Logo_bus.jpg.
        /// </summary>
        internal static string Logo_bus_jpg {
            get {
                return ResourceManager.GetString("Logo_bus.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\logoSTB.png.
        /// </summary>
        internal static string logoSTB_png {
            get {
                return ResourceManager.GetString("logoSTB.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\metro_video.mp4.
        /// </summary>
        internal static string metro_video_mp4 {
            get {
                return ResourceManager.GetString("metro_video.mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\PublicTransport.mp4.
        /// </summary>
        internal static string PublicTransport_mp4 {
            get {
                return ResourceManager.GetString("PublicTransport.mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Road.jpg.
        /// </summary>
        internal static string Road_jpg {
            get {
                return ResourceManager.GetString("Road.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\simple_map.png.
        /// </summary>
        internal static string simple_map_png {
            get {
                return ResourceManager.GetString("simple_map.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\tram_im.jpg.
        /// </summary>
        internal static string tram_im_jpg {
            get {
                return ResourceManager.GetString("tram_im.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\tram_video.mp4.
        /// </summary>
        internal static string tram_video_mp4 {
            get {
                return ResourceManager.GetString("tram_video.mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\tram1.gif.
        /// </summary>
        internal static string tram1_gif {
            get {
                return ResourceManager.GetString("tram1.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\tram2.gif.
        /// </summary>
        internal static string tram2_gif {
            get {
                return ResourceManager.GetString("tram2.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\tram3.gif.
        /// </summary>
        internal static string tram3_gif {
            get {
                return ResourceManager.GetString("tram3.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\umbrelas.jpg.
        /// </summary>
        internal static string umbrelas_jpg {
            get {
                return ResourceManager.GetString("umbrelas.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\video_ceva.mp4.
        /// </summary>
        internal static string video_ceva_mp4 {
            get {
                return ResourceManager.GetString("video_ceva.mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\wallpaper.jpg.
        /// </summary>
        internal static string wallpaper_jpg {
            get {
                return ResourceManager.GetString("wallpaper.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\wallpaper_new.jpg.
        /// </summary>
        internal static string wallpaper_new_jpg {
            get {
                return ResourceManager.GetString("wallpaper_new.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\wallpaper_p1.jpg.
        /// </summary>
        internal static string wallpaper_p1_jpg {
            get {
                return ResourceManager.GetString("wallpaper_p1.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\wallpaper1.jpg.
        /// </summary>
        internal static string wallpaper1_jpg {
            get {
                return ResourceManager.GetString("wallpaper1.jpg", resourceCulture);
            }
        }
    }
}
