//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Components.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus1.gif.
        /// </summary>
        internal static string bus1_gif {
            get {
                return ResourceManager.GetString("bus1.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus2.gif.
        /// </summary>
        internal static string bus2_gif {
            get {
                return ResourceManager.GetString("bus2.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus3.gif.
        /// </summary>
        internal static string bus3_gif {
            get {
                return ResourceManager.GetString("bus3.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus4.gif.
        /// </summary>
        internal static string bus4_gif {
            get {
                return ResourceManager.GetString("bus4.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus5.gif.
        /// </summary>
        internal static string bus5_gif {
            get {
                return ResourceManager.GetString("bus5.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\bus6.gif.
        /// </summary>
        internal static string bus6_gif {
            get {
                return ResourceManager.GetString("bus6.gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\Home_LeftSide_Bar.png.
        /// </summary>
        internal static string Home_LeftSide_Bar_png {
            get {
                return ResourceManager.GetString("Home_LeftSide_Bar.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\Home_LeftSide_Bar2.png.
        /// </summary>
        internal static string Home_LeftSideBar2_png {
            get {
                return ResourceManager.GetString("Home_LeftSideBar2.png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\Pupils_Facilities_Background.jpg.
        /// </summary>
        internal static string Pupils_Facilities_Background_jpg {
            get {
                return ResourceManager.GetString("Pupils_Facilities_Background.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\Student_Facilities_Background.jpg.
        /// </summary>
        internal static string Student_Facilities_Background_jpg {
            get {
                return ResourceManager.GetString("Student_Facilities_Background.jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Home_Images\tram4.gif.
        /// </summary>
        internal static string tram4_gif {
            get {
                return ResourceManager.GetString("tram4.gif", resourceCulture);
            }
        }
    }
}
