//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angajat()
        {
            this.MTs = new HashSet<MT>();
        }
    
        public int id_unic { get; set; }
        public decimal salariu { get; set; }
        public int id_persoana { get; set; }
        public int tip_angajat { get; set; }
        public System.DateTime data_angajarii { get; set; }
    
        public virtual Persoana Persoana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT> MTs { get; set; }
        public virtual Tip_Angajat Tip_Angajat1 { get; set; }
    }
}
