//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int id_unic { get; set; }
        public int id_user { get; set; }
        public string text_plangere { get; set; }
        public int id_tip_MTC { get; set; }
    
        public virtual TipMT TipMT { get; set; }
        public virtual User User { get; set; }
    }
}
