//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT
    {
        public int id_unic { get; set; }
        public int id_tip { get; set; }
        public int nr_traseu { get; set; }
        public string nr_inmatriculare { get; set; }
        public int id_sofer { get; set; }
        public int numar_mt { get; set; }
    
        public virtual Angajat Angajat { get; set; }
        public virtual TipMT TipMT { get; set; }
        public virtual Traseu Traseu { get; set; }
    }
}
