//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statie
    {
        public int id_unic { get; set; }
        public int id_traseu { get; set; }
        public int id_tip_statie { get; set; }
        public string ore { get; set; }
    
        public virtual Traseu Traseu { get; set; }
        public virtual Tip_Statie Tip_Statie { get; set; }
    }
}
